### ISSUE TITLE
Update documentation archive process to work with new site

### ISSUE THREAD

**Issue by mraible** [jhipster/jhipster-ansible#12]
The new website uses Docusaurus instead of Jekyll, so we need to modify scripts to accommodate this change and add the appropriate banner at the top.

**Comment by SvMak** [comment]
@mraible Could you please check the solution to speed up the release of 8.7.1?

**Comment by mraible** [comment]
I tried checking out your branch from #13 and running `ansible-playbook -v playbooks/generator-jhipster-prepare.yml`. It seems to create the site OK, but when I tried to serve it from a parent directory, it gave me an error.

<img width="1462" alt="Screenshot 2024-09-20 at 14 52 18" src="https://github.com/user-attachments/assets/d60afa73-2cd5-40b1-8ed4-4b45e1fa1859">

I'm guessing this is because https://github.com/jhipster/jhipster.github.io/pull/1390 needs to be merged before it will work?

**Comment by SvMak** [comment]
> I tried checking out your branch from #13 and running `ansible-playbook -v playbooks/generator-jhipster-prepare.yml`. It seems to create the site OK, but when I tried to serve it from a parent directory, it gave me an error.
> 
> <img alt="Screenshot 2024-09-20 at 14 52 18" width="1462" src="https://private-user-images.githubusercontent.com/17892/369551465-d60afa73-2cd5-40b1-8ed4-4b45e1fa1859.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4NjYwMjEsIm5iZiI6MTcyNjg2NTcyMSwicGF0aCI6Ii8xNzg5Mi8zNjk1NTE0NjUtZDYwYWZhNzMtMmNkNS00MGIxLThlZDQtNGI0NWUxZmExODU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDIwNTUyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjZWVkZGI0ZjUxNzFiM2RiNmQzMWVlMWU3NmYwNjU5YjNiNTJmNGI0MTE2MGYwY2EzZjcwODRjNjFhMDliMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Oju3xd34V_Oe4RiwMT-sPRVzMYGcjoFy-vD2_Eq_e2k">
> I'm guessing this is because [jhipster/jhipster.github.io#1390](https://github.com/jhipster/jhipster.github.io/pull/1390) needs to be merged before it will work?

Yes, absolutely right, you need merge updates for jhipster.github.io

**Comment by mraible** [comment]
I tried that locally and it looks good! 

<img width="1482" alt="Screenshot 2024-09-20 at 15 04 11" src="https://github.com/user-attachments/assets/fb30d4e8-f3f4-44ec-ba74-d669422e07fa">

I'll work on merging these and do the release tomorrow.

**Comment by SvMak** [comment]
@mraible To fix the old documentation archive I made two PRs and they both need to be merged.
